apiVersion: v1
kind: ServiceAccount
metadata:
  name: notiflex-api-sa
  namespace: enterprise
  annotations:
    iam.gke.io/gcp-service-account: notiflex-app@project-75fce205-dfa5-4975-a56.iam.gserviceaccount.com
